services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3087:3087"
    environment:
      - ASPNETCORE_URLS=http://+:3087
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Userid=postgres;Password=postgres;SslMode=Disable;Database=todos
      - Jwt__Key=ThisIsASecretKeyForJwtTokenGeneration
    command: sh -c "sleep 10 && dotnet run"
